#define TOP_LEFT_CHASSIS 14
#define BOTTOM_LEFT_CHASSIS 1
#define TOP_RIGHT_CHASSIS 4
#define BOTTOM_RIGHT_CHASSIS 16

#define FRONT_ARM_LEFT 3
#define FRONT_ARM_RIGHT 2
#define CONVEYOR 11

#define FRONT_CLAW 'A'
#define BACK_CLAW 13

#define REAR_TRACKING_UPPER 'A'
#define REAR_TRACKING_LOWER 'B'