#define TOP_LEFT_CHASSIS 14
#define BOTTOM_LEFT_CHASSIS 1
#define TOP_RIGHT_CHASSIS 4
#define BOTTOM_RIGHT_CHASSIS 16
// #define TOP_LEFT_CHASSIS 6
// #define BOTTOM_LEFT_CHASSIS 7
// #define TOP_RIGHT_CHASSIS 8
// #define BOTTOM_RIGHT_CHASSIS 21

#define WHEEL_DIAMETER 0.08255

#define FRONT_ARM_LEFT 7
#define FRONT_ARM_RIGHT 2
#define CONVEYOR 11

#define FRONT_CLAW 'C'
#define BACK_CLAW 13

#define ARM_POTENTIOMETER 'D'
#define ARM_UPPER_LIMIT 2700
#define ARM_LOWER_LIMIT 1350

#define REAR_TRACKING_UPPER 'A'
#define REAR_TRACKING_LOWER 'B'