#define TOP_LEFT_CHASSIS 8
#define BOTTOM_LEFT_CHASSIS 9
#define TOP_RIGHT_CHASSIS 6
#define BOTTOM_RIGHT_CHASSIS 7

#define FRONT_LEFT_ARM 4
#define FRONT_RIGHT_ARM 3
#define BACK_ARM 12
#define CONVEYOR 5

#define FRONT_CLAW 'A'
#define BACK_CLAW 'B'

#define LEFT_TRACKING_UPPER 'A'
#define LEFT_TRACKING_LOWER 'B'
#define RIGHT_TRACKING_UPPER 'C'
#define RIGHT_TRACKING_LOWER 'D'
#define REAR_TRACKING_UPPER 'E'
#define REAR_TRACKING_LOWER 'F'